[program:so2_sync_watchdog]
user=ubuntu
command=/usr/bin/python3 -u /etc/supervisor/userScripts/py_data_watchdog/run_me.py
autostart=true
autorestart=true
stderr_logfile=/var/log/%(program_name)s.out.log
stdout_logfile=/var/log/%(program_name)s.out.log

stdout_logfile_maxbytes=10000
stderr_logfile_maxbytes=10000

stdout_logfile_backups=10
stderr_logfile_backups=10

